//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiService.Resource {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationErrorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationErrorResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApiService.Resource.ApplicationErrorResource", typeof(ApplicationErrorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   アカウント作成に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccounCreatFailedError {
            get {
                return ResourceManager.GetString("AccounCreatFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   既に使用されているユーザIDです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AlreadyExitsAccountError {
            get {
                return ResourceManager.GetString("AlreadyExitsAccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {1}文字以内で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EnterWithInMaxLengthError {
            get {
                return ResourceManager.GetString("EnterWithInMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログインに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再ログインを行ってください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotActiveUserError {
            get {
                return ResourceManager.GetString("NotActiveUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   勤怠データが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotDataAttendanceError {
            get {
                return ResourceManager.GetString("NotDataAttendanceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象の勤怠データが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotDataAttendanceTargetError {
            get {
                return ResourceManager.GetString("NotDataAttendanceTargetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新対象の勤怠がありませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotDataAttendanceUpdateError {
            get {
                return ResourceManager.GetString("NotDataAttendanceUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   本日、未退勤の勤怠データがあります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotRegistAttendanceClockOutError {
            get {
                return ResourceManager.GetString("NotRegistAttendanceClockOutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   有効なユーザーではありません。再度ログインを行ってください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotValidUserError {
            get {
                return ResourceManager.GetString("NotValidUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出退勤日時は必須です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OutClockDateRequiredError {
            get {
                return ResourceManager.GetString("OutClockDateRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   success に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UnexpectedError に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーIDまたはパスワードが無効です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserIdOrPasswordInvalidError {
            get {
                return ResourceManager.GetString("UserIdOrPasswordInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidateParamError {
            get {
                return ResourceManager.GetString("ValidateParamError", resourceCulture);
            }
        }
    }
}
