//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiService.Resource {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApiService.Resource.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   AttendanceId に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyIdAttendanceId {
            get {
                return ResourceManager.GetString("KeyIdAttendanceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyIdPassword {
            get {
                return ResourceManager.GetString("KeyIdPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyIdUserId {
            get {
                return ResourceManager.GetString("KeyIdUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyIdUserName {
            get {
                return ResourceManager.GetString("KeyIdUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワード。例: Password123 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SWDescriptionPassword {
            get {
                return ResourceManager.GetString("SWDescriptionPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新理由。例: 勤怠登録忘れのため。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SWDescriptionReason {
            get {
                return ResourceManager.GetString("SWDescriptionReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象月（UTC）のUNIX時間（秒）。例: 1672531200 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SWDescriptionTargetDateUtcUnixTimeSec {
            get {
                return ResourceManager.GetString("SWDescriptionTargetDateUtcUnixTimeSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーコード。例: user123 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SWDescriptionUserCode {
            get {
                return ResourceManager.GetString("SWDescriptionUserCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー名。例: 山田 太郎 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SWDescriptionUserName {
            get {
                return ResourceManager.GetString("SWDescriptionUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   勤務日のUNIX時間（秒）。例: 1672531200 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SWDescriptionWorkDateUserUnixTimeSec {
            get {
                return ResourceManager.GetString("SWDescriptionWorkDateUserUnixTimeSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   勤務形態。 1:出社、2:在宅、3:外出 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SWDescriptionWorkingStyleState {
            get {
                return ResourceManager.GetString("SWDescriptionWorkingStyleState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   勤怠IDは必須です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SWRequiredAttendanceId {
            get {
                return ResourceManager.GetString("SWRequiredAttendanceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出勤時刻（UTC）のUNIX時間（秒）は必須です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SWRequiredClockInDateUtcUnixTimeSec {
            get {
                return ResourceManager.GetString("SWRequiredClockInDateUtcUnixTimeSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出退勤日時は必須です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SWRequiredClockInOutDateTimeUserUnixTimeSec {
            get {
                return ResourceManager.GetString("SWRequiredClockInOutDateTimeUserUnixTimeSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   履歴時刻（UTC）のUNIX時間（秒）は必須です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SWRequiredGenerateDateUtcUnixTimeSec {
            get {
                return ResourceManager.GetString("SWRequiredGenerateDateUtcUnixTimeSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードは必須です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SWRequiredPassword {
            get {
                return ResourceManager.GetString("SWRequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新理由は必須です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SWRequiredReason {
            get {
                return ResourceManager.GetString("SWRequiredReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象月は必須です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SWRequiredTargetDateUtcUnixTimeSec {
            get {
                return ResourceManager.GetString("SWRequiredTargetDateUtcUnixTimeSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーコードは必須です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SWRequiredUserCode {
            get {
                return ResourceManager.GetString("SWRequiredUserCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー名は必須です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SWRequiredUserName {
            get {
                return ResourceManager.GetString("SWRequiredUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   勤務日のUNIX時間（秒）は必須です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SWRequiredWorkDateUserUnixTimeSec {
            get {
                return ResourceManager.GetString("SWRequiredWorkDateUserUnixTimeSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新理由は必須です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SWRequiredWorkingReason {
            get {
                return ResourceManager.GetString("SWRequiredWorkingReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   勤務形態は必須です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SWRequiredWorkingStyleState {
            get {
                return ResourceManager.GetString("SWRequiredWorkingStyleState", resourceCulture);
            }
        }
    }
}
